name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  publish-npm:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "nooooru@gmail.com"
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: |
          npm version patch
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: |
          git show
          git push